cat("pollutantmean.R\n")
cat("===============\n")
source("pollutantmean.R")
print(pollutantmean("specdata", "sulfate", 1:10))
print(pollutantmean("specdata", "nitrate", 70:72))
print(pollutantmean("specdata", "nitrate", 23))
cat("\n")

cat("complete.R\n")
cat("==========\n")
source("complete.R")
print(complete("specdata", 1))
cat("\n")
print(complete("specdata", c(2, 4, 8, 10, 12)))
cat("\n")
print(complete("specdata", 30:25))
cat("\n")
print(complete("specdata", 3))
cat("\n")

cat("corr.R\n")
cat("======\n")
source("corr.R")
source("complete.R")

cat("corr(\"specdata\", 150)\n")
cat("=====================\n")
cr <- corr("specdata", 150)
print(head(cr))
cat("\n")
print(summary(cr))
cat("\n\n")

cat("corr(\"specdata\", 400)\n")
cat("=====================\n")
cr <- corr("specdata", 400)
print(head(cr))
cat("\n")
print(summary(cr))
cat("\n\n")

cat("corr(\"specdata\", 5000)\n")
cat("======================\n")
cr <- corr("specdata", 5000)
print(summary(cr))
cat("\n")
print(length(cr))
cat("\n")

cat("corr(\"specdata\")\n")
cat("================\n")
cr <- corr("specdata")
print(summary(cr))
cat("\n")
print(length(cr))
cat("\n")
